# Generated by Django 4.2.30 on 2026-09-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito', models.CharField(choices=[('derecho', 'Derecho'), ('internacional', 'Ámbito internacional'), ('transversal', 'Enfoque transversal')], default='derecho', max_length=20, verbose_name='ámbito')),
                ('titulo', models.CharField(max_length=140, verbose_name='título')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='identificador')),
                ('resumen', models.CharField(max_length=240, verbose_name='resumen')),
                ('descripcion', models.TextField(blank=True, help_text='Separa los párrafos con una línea en blanco.', verbose_name='descripción')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('publicada', models.BooleanField(default=True, verbose_name='publicada')),
            ],
            options={
                'verbose_name': 'área de interés profesional',
                'verbose_name_plural': 'áreas de interés profesional',
                'ordering': ('orden', 'titulo'),
            },
        ),
        migrations.CreateModel(
            name='HitoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('formacion', 'Formación académica'), ('trayectoria', 'Trayectoria profesional'), ('investigacion', 'Investigación y publicaciones')], default='formacion', max_length=20, verbose_name='categoría')),
                ('titulo', models.CharField(max_length=160, verbose_name='título')),
                ('institucion', models.CharField(blank=True, max_length=160, verbose_name='institución')),
                ('periodo', models.CharField(blank=True, max_length=80, verbose_name='periodo')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('publicado', models.BooleanField(default=True, verbose_name='publicado')),
            ],
            options={
                'verbose_name': 'hito de formación o trayectoria',
                'verbose_name_plural': 'hitos de formación y trayectoria',
                'ordering': ('orden', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PerfilProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(default='Adriana Lara Gutiérrez', max_length=120, verbose_name='nombre completo')),
                ('titular', models.CharField(default='Perfil Académico en Derecho y Relaciones Internacionales', help_text='Fórmula de presentación. No atribuir titulaciones definitivas que no estén acreditadas.', max_length=160, verbose_name='titular')),
                ('presentacion', models.TextField(default='Análisis jurídico con visión internacional. Mi enfoque combina rigor técnico, claridad expositiva y respeto a los principios deontológicos de la profesión, en asuntos donde confluyen el ordenamiento nacional, el europeo y el internacional.', help_text='Separa los párrafos con una línea en blanco.', verbose_name='presentación')),
                ('situacion', models.CharField(blank=True, default='Próxima graduación', help_text='Texto del sello de la ficha. Déjalo vacío para ocultarlo.', max_length=60, verbose_name='situación actual')),
                ('numero_colegiada', models.CharField(default='[Nº Colegiada pendiente de colegiación / Editable]', help_text='Mientras no exista colegiación, mantén el marcador entre corchetes. Sustitúyelo por el número real cuando proceda.', max_length=80, verbose_name='número de colegiada')),
                ('colegio_profesional', models.CharField(blank=True, max_length=160, verbose_name='colegio profesional')),
                ('idiomas', models.CharField(blank=True, max_length=160, verbose_name='idiomas de trabajo')),
                ('ciudad', models.CharField(blank=True, max_length=120, verbose_name='ubicación')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='perfil profesional (URL)')),
                ('lema_juzgado', models.CharField(default='El rigor jurídico se construye con fuentes, método y criterio.', max_length=200, verbose_name='lema (franja del juzgado)')),
                ('lema_internacional', models.CharField(default='Un mismo asunto, varios ordenamientos: todo análisis empieza por saber cuál se aplica.', max_length=200, verbose_name='lema (franja internacional)')),
                ('aviso_legal', models.TextField(default='La información publicada en este sitio tiene carácter exclusivamente informativo y académico. No constituye asesoramiento jurídico ni establece relación profesional alguna entre abogado y cliente.\n\nEl contenido describe un perfil académico. Los datos de colegiación se publicarán únicamente cuando exista la correspondiente inscripción en el colegio profesional, y las titulaciones se indicarán solo una vez acreditadas.', verbose_name='aviso legal y deontológico')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
            ],
            options={
                'verbose_name': 'perfil profesional',
                'verbose_name_plural': 'perfil profesional',
            },
        ),
        migrations.CreateModel(
            name='Principio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='título')),
                ('texto', models.TextField(verbose_name='texto')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('publicado', models.BooleanField(default=True, verbose_name='publicado')),
            ],
            options={
                'verbose_name': 'criterio de trabajo',
                'verbose_name_plural': 'criterios de trabajo',
                'ordering': ('orden', 'id'),
            },
        ),
    ]
